
spring:
  h2:
    console:
      enabled: 'true'
      path: /h2
  datasource:
    url: jdbc:h2:mem:dogapi

cloud:
  aws:
    credentials:
      access-key: 
      secret-key: 
    region:
      static: ap-southeast-1
    stack:
      auto: false

application:
  bucket:
    name: dog-api-thang-demo

keycloak:
  auth-server-url: http://localhost:8180
  realm: dogapi2
  public-client: 'true'
  bearer-only: 'true'
  resource: dog-client
